#ifndef _COMMDEF_H_
#define _COMMDEF_H_

// Define the various device type values. Note that values used by Microsoft
// Corporation are in the range 0-32767, and 32768-65535 are reserved for use
// by customers.
#define FILE_DEVICE_HDHOOK		0x00008305

// Commands that the GUI can send the device driver
#define IOCTL_HDHOOK_HOOK			(ULONG) CTL_CODE( FILE_DEVICE_HDHOOK, 0x00, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_HDHOOK_UNHOOK			(ULONG) CTL_CODE( FILE_DEVICE_HDHOOK, 0x01, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_HDHOOK_GETVERSION		(ULONG) CTL_CODE( FILE_DEVICE_HDHOOK, 0x02, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_HDHOOK_SETOLDVALUE	(ULONG) CTL_CODE( FILE_DEVICE_HDHOOK, 0x03, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_HDHOOK_SETNEWVALUE	(ULONG) CTL_CODE( FILE_DEVICE_HDHOOK, 0x04, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define IOCTL_HDHOOK_SETFILTER		(ULONG) CTL_CODE( FILE_DEVICE_HDHOOK, 0x05, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define DRIVER_NAME					L"HDHOOK"
#define SERVICE_NAME				"HDHOOK"
#define DRIVER_FILE_NAME			"HDHook.sys"
#define PROFILE_APP_NAME			"HDHOOK"
#define PROFILE_KEY_NAME_SERIAL		"SerialNumber"
#define PROFILE_KEY_NAME_MODEL		"ModelName"
#define PROFILE_KEY_NAME_INCLUDE	"Include"
#define PROFILE_KEY_NAME_EXCLUDE	"Exclude"
#define PROFILE_KEY_NAME_AUTOEND	"AutoEnd"
#define PROFILE_KEY_NAME_AUTORUN	"Twister"

// Version #
#define HDHOOK_VERSION		300

#define IDE_ATA_IDENTIFY	0xEC	// ATA
#define IDE_ATAPI_IDENTIFY	0xA1	// ATAPI

#define DISK_SERIAL_BUFF_LENGTH		20
#define DISK_MODEL_BUFF_LENGTH		40
#define FILTER_MAX_LENGTH 250

typedef struct _DISKINFO
{
	CHAR sSerialNumber[DISK_SERIAL_BUFF_LENGTH+1];
	CHAR sModelNumber[DISK_MODEL_BUFF_LENGTH+1];
} DISKINFO;

typedef struct _FILTER
{
	CHAR IncludeFilter[FILTER_MAX_LENGTH+1];
	CHAR ExcludeFilter[FILTER_MAX_LENGTH+1];
} FILTER, *PFILTER;

#endif
